### ISSUE TITLE
Crash trying to open a directory

### ISSUE THREAD

**Issue by bparker06** [byuu/bsnes#130]
I went to System -> Load Game, then typed in the name of a directory and pressed enter. Normally in other applications this would cause the directory contents to be shown, as if I'd double-clicked on the directory entry in the listing... but bsnes crashes when I do this. Backtrace is attached:

```
Thread 1 "bsnes" received signal SIGSEGV, Segmentation fault.
0x00005555556b93d1 in nall::vector_base<unsigned char>::resizeRight (this=this@entry=0x7fffffffbaf0, size=9223372036854775807, value=value@entry=@0x7fffffffa920: 0 '\000') at /usr/include/c++/9.1.0/new:174
174	{ return __p; }
(gdb) print __p
No symbol "__p" in current context.
(gdb) bt
#0  0x00005555556b93d1 in nall::vector_base<unsigned char>::resizeRight(unsigned long, unsigned char const&) (this=this@entry=0x7fffffffbaf0, size=9223372036854775807, value=value@entry=@0x7fffffffa920: 0 '\000')
    at /usr/include/c++/9.1.0/new:174
#1  0x00005555556b951c in nall::vector_base<unsigned char>::resize(unsigned long, unsigned char const&) (value=@0x7fffffffa920: 0 '\000', size=<optimized out>, this=0x7fffffffbaf0) at ../nall/vector.hpp:61
#2  0x00005555556b951c in nall::file::read(nall::string const&) (filename=...) at ../nall/file.hpp:77
#3  0x000055555586101f in Program::loadFile(nall::string) (this=this@entry=0x55555d384120 <program>, location=...) at target-bsnes/program/game.cpp:98
#4  0x000055555587bda9 in Program::loadSuperFamicom(nall::string) (this=this@entry=0x55555d384120 <program>, location=...) at ../nall/string.hpp:138
#5  0x000055555587cfd1 in Program::load(unsigned int, nall::string, nall::string, nall::vector<nall::string>) (this=this@entry=0x55555d384120 <program>, id=id@entry=1, name=..., type=..., options=...) at ../nall/string.hpp:138
#6  0x0000555555747826 in SuperFamicom::Cartridge::load() (this=0x555555cfac00 <SuperFamicom::cartridge>) at ../nall/string/core.hpp:53
#7  0x000055555572ccc2 in SuperFamicom::System::load(Emulator::Interface*) (this=0x555555a04680 <SuperFamicom::system>, interface=0x55555dda6e40) at sfc/system/system.cpp:55
#8  0x00005555557234af in SuperFamicom::Interface::load() (this=<optimized out>) at sfc/interface/interface.cpp:78
#9  0x0000555555872c60 in Program::load() (this=0x55555d384120 <program>) at ../nall/unique-pointer.hpp:29
#10 0x000055555589d924 in Presentation::<lambda()>::operator() (__closure=<optimized out>) at target-bsnes/presentation/presentation.cpp:8
#11 0x000055555589d924 in nall::function<void()>::lambda<Presentation::create()::<lambda()> >::operator()(void) const (this=<optimized out>) at ../nall/function.hpp:72
#12 0x00005555556513b7 in nall::function<void ()>::operator()() const (this=<optimized out>) at ../nall/function.hpp:29
#13 0x00005555556513b7 in hiro::mMenuItem::doActivate() const (this=<optimized out>) at ../hiro/core/action/menu-item.cpp:10
#14 0x00005555556513ca in hiro::MenuItem_activate(GtkMenuItem*, hiro::pMenuItem*) (p=<optimized out>) at ../hiro/core/../gtk/action/menu-item.hpp:6
```

Using Linux x64 with GCC 9.1.0

**Comment by byuu** [comment]
It doesn't crash for me when I try this, but all the same, it should've entered the folder instead of trying to load it when the folder didn't end in ".sfc" (eg a gamepak).

Fixed for the next WIP, thanks.
